### PR TITLE
feat(API update): Update to latest API definitions.

### PR DESCRIPTION
**Pull request by martinpovolny**
With the semantic-release compatible commit message and the actual updated swagger file @Hyperkid123 ;-)

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]

**Comment by Hyperkid123** [comment]
I've restarted Travis. I will merge after its green.

**Comment by Hyperkid123** [comment]
@martinpovolny is this rebased on latest master? There seem to be git tags mismatch which causes issues with travis.

**Comment by martinpovolny** [comment]
> I've restarted Travis. I will merge after its green.

Tried that. It did not help.

**Pull request merged**
